[package]
name = "wallet"
version = "0.1.6"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
tera = "1.20.0"
tokio = {version = "1.44.1", features = ["full"] }

[[bin]]
name = "wallet"
path = "src/main.rs"

[lib]
name = "wallet"
path = "src/lib.rs"
